- hosts: all
  tasks:
    - name: Clone of a single branch
      ansible.builtin.git:
          repo: "{{ scm_url }}"
          dest: "{{ project_path }}"
          version: main

    - name: Build container
      shell: cd "{{ project_path }}" &&  docker build -t test:"{{ version }}" .

    - name: Stop and remove old container
      shell: docker kill $(docker ps -q)

    - docker_container:
      name: backend
      image: test:{{ version }}
      env:
        TEST: "1234"
      state: started
      ports:
        - "3000:3000"
