- hosts: all
  tasks:
    - name: Clone of a single branch
      ansible.builtin.git:
          repo: "{{ scm_url }}"
          dest: "{{ project_path }}"
          version: main

    - name: Build container
      shell: cd "{{ project_path }}" &&  docker build -t test:1.0 .