- hosts: all
  tasks:
    - name: Clone of a single branch
      ansible.builtin.git:
          repo: "{{ scm_url }}"
          dest: "{{ project_path }}"
          version: main

    - name: Build container
      shell: cd "{{ project_path }}" &&  docker build -t test:"{{ version }}" .

    - name: Stop and remove old container
      shell: docker kill $(docker ps -q)
      ignore_errors: yes

    - community.docker.docker_image:
        source: local
        name: backend
        image: test:{{ version }}
        env:
          TEST: "1234"
        state: present
        ports:
          - "3000:3000"
